---
title: "Final Report"
format: html
editor: visual
---

## Data

We are exploring the relationship between child mortality and average daily income. \
In case of child mortality, our data source provides a the number of the deaths of children under 5 years of age per 1000 live births for a certain country during a certain year. We have data for the years 1800 to 2100. \
There are three separate sources for this data, depending on the year.

-   **1800–1950 (and intermittently beyond):** Data come from Gapminder version 7, assembled by Klara Johansson and Mattias Lindgren. It draws primarily on mortality.org and Brian R. Mitchell’s International Historical Statistics. Infant mortality estimates were statistically converted into child mortality figures.

-   **1950–2016:** The UN Inter‐agency Group for Child Mortality Estimation (UN IGME)—a partnership of UNICEF, WHO, the UN Population Division, and the World Bank—produced these estimates. Their publicly released country and global child-mortality series (available at childmortality.org) extend back to 1950 for some nations, cover 1960 for about half, and span 1970–2018 for 70% of all countries.

-   **1950–2100:** The UN’s World Population Prospects 2019 provides harmonized annual child-mortality rates for every country including both historical values and projections through 2100.

In case of average daily income, we are analyzing the survey-derived average daily household income or consumption per person, adjusted to 2017 prices in constant international dollars (PPP).\
Similarly, there are different sources for different years.

-   **1981-2019:** Data is collected from the World Bank. For the countries missing from the World Bank, the number is estimated using the mean income based on the country GDP per capita. That data itself also has many sources, including the World Bank, Maddison Project Database, and IMF.

-   **1800-1981 and 2019-2100:** These numbers are estimed using the growth rates of the constant dollar GDP per capita. These are rough estimates.
